### ISSUE TITLE
Very similar to https://github.com/alexyoung/dailyjs-backbone-tutorial/issues/5

### ISSUE THREAD

**Issue by bjpcjp** [alexyoung/dailyjs-backbone-tutorial#6]
Also starting tutorial & ran into the error at "npm run-script grunt":

> btask@0.0.1 grunt /home/bjpcjp/projects/backbone/dailyjs-tutorial/fresh
> node_modules/.bin/grunt

Warning: Task "exec copy-require" not found. Use --force to continue.

Aborted due to warnings.
npm ERR! btask@0.0.1 grunt: `node_modules/.bin/grunt`
npm ERR! `sh "-c" "node_modules/.bin/grunt"` failed with 3
npm ERR! 
npm ERR! Failed at the btask@0.0.1 grunt script.
npm ERR! This is most likely a problem with the btask package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/.bin/grunt
npm ERR! You can get their info via:
npm ERR!     npm owner ls btask
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-39-generic-pae
npm ERR! command "nodejs" "/usr/bin/npm" "run-script" "grunt"
npm ERR! cwd /home/bjpcjp/projects/backbone/dailyjs-tutorial/fresh
npm ERR! node -v v0.8.18
npm ERR! npm -v 1.2.2
npm ERR! code ELIFECYCLE

package.json already includes:
"grunt": "0.4.x" , 
"grunt-exec": "0.4.x", 
"grunt-cli": "0.1.x"

Suggestions?

**Comment by eriksjaastad** [comment]
Thanks Prashant! That solved my issue.
